<?xml version="1.0" encoding="utf-8"?><Database Name="ElectroShop" Class="dbElectroShopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.ADMIN" Member="ADMINs">
    <Type Name="ADMIN">
      <Column Name="MaAd" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TenDN" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Quyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETDATHANG" Member="CHITIETDATHANGs">
    <Type Name="CHITIETDATHANG">
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Association Name="DONDATHANG_CHITIETDATHANG" Member="DONDATHANG" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="DONDATHANG" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETDATHANG" Member="SANPHAM" ThisKey="MaSP" OtherKey="MaSP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONDATHANG" Member="DONDATHANGs">
    <Type Name="DONDATHANG">
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DaThanhToan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TinhTrangGiaoHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NgayGiao" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="DONDATHANG_CHITIETDATHANG" Member="CHITIETDATHANGs" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="CHITIETDATHANG" />
    </Type>
  </Table>
  <Table Name="dbo.HANG" Member="HANGs">
    <Type Name="HANG">
      <Column Name="MaHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="HANG_SANPHAM" Member="SANPHAMs" ThisKey="MaHang" OtherKey="MaHang" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.LOAISP" Member="LOAISPs">
    <Type Name="LOAISP">
      <Column Name="MaLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LOAISP_SANPHAM" Member="SANPHAMs" ThisKey="MaLoai" OtherKey="MaLoai" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AnhBia" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SoLuongBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="MaLoai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SANPHAM_CHITIETDATHANG" Member="CHITIETDATHANGs" ThisKey="MaSP" OtherKey="MaSP" Type="CHITIETDATHANG" />
      <Association Name="LOAISP_SANPHAM" Member="LOAISP" ThisKey="MaLoai" OtherKey="MaLoai" Type="LOAISP" IsForeignKey="true" />
      <Association Name="HANG_SANPHAM" Member="HANG" ThisKey="MaHang" OtherKey="MaHang" Type="HANG" IsForeignKey="true" />
    </Type>
  </Table>
</Database>